services:
  dggpt:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dggpt
    volumes:
      - ./config:/dggpt/config
      - ./mp3files:/dggpt/mp3files
    restart: unless-stopped
